<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$model = $objectManager->create('\DCKAP\Welcome\Model\Models')->load(1);
echo "<pre>";print_r($model->getData());echo "</pre>";

?>
<strike> Magento 1</strike> Magento 2
<h1> Welcome to Magento 2 </h2>
<?php echo 'This is the Simple Welcome Module in Magento 2.0';?>
<?php echo $this->getChildHtml('hello_fine');?>
<p id="test"></p>
<script>
 require(['jquery', 'jquery/ui'], function($){ 
    $(document).ready(function(){		
		 $.ajax({				
				url: '<?php echo $this->getUrl('welcome/ajax/ajax')?>',				
				type: "POST",
				
			}).done(function (data) {
				$('#test').html(data);
			});
	});
 });
</script>